/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - An odxml42 Tool
    This file WILL NOT be overwritten once changes are made.
*************************************************/
using System;
using System.ComponentModel;
                        
namespace authorizersbysubscription.Lib.DataClasses
{                   
    
    public partial class ProductVersion 
    {
        public ProductVersion()
        {
            this.InitPoco();
        }

        public override String ToString()
        {
            return String.Format("ProductVersion: {0}", this.Name);
        }
                            
    }
}