/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - An odxml42 Tool
    This file WILL NOT be overwritten once changes are made.
*************************************************/
using EffortlessAPI.SSio.SassyMQ;
using System;
using System.Collections.Generic;
using System.ComponentModel;
                        
namespace SmartSubs.io.Lib.DataClasses
{                   
    
    public partial class BrandLicense 
    {
        public BrandLicense()
        {
            this.InitPoco();
        }

        public override String ToString()
        {
            return String.Format("BrandLicense: {0}", this.Name);
        }

        public static List<BrandLicense> GetBrandLicenses(string brandPrefix)
        {
            var licenses = new List<BrandLicense>();
            var guest = new SMQGuest(SMQGuest.C_AMQPS);
            var payload = guest.CreatePayload();
            guest.GetBrandLicenses(payload, (reply, bdea) =>
            {
                if (reply.HasNoErrors(bdea))
                {
                    licenses = reply.BrandLicenses;
                }
            }).Wait(30000);
            return licenses;
        }
    }
}